name: Monitor Documentacion

on:
  schedule:
    # Opción A (cada 15 min): 07:00–13:45 UTC (08:00–14:45 CET) + ejecución a las 14:00 UTC (15:00 CET)
    # - cron: "*/15 7-13 * * 1-5"
    # - cron: "0 14 * * 1-5"

    # Opción B (cada 30 min): 07:00–13:30 UTC (08:00–14:30 CET) + ejecución a las 14:00 UTC (15:00 CET)
    - cron:  "*/15 7-13 * * 1-5"
    - cron: "0 14 * * 1-5"

  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run monitor
        run: |
          python check_docs.py

      - name: Commit state if changed
        run: |
          if git diff --quiet; then
            echo "No hay cambios que commitear."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add state.json
          git commit -m "Actualiza estado Documentación"
          git push
